### ISSUE TITLE
尝试使用Transifex平台进行翻译

### ISSUE THREAD

**Issue by caizixian** [rustcc/rust-zh#33]
https://www.transifex.com/organization/rust-i18n/dashboard
大家可以在issue里评论下，我把大家加入到维护者里。

Transifex最大的好处就是有翻译记忆，不用重复翻译。并且还能自动从upstream获取更新，不用手工操作。

@liigo @alwayrun @M-Adoo @doomsplayer @tennix @geekcraik @lidashuang

**Comment by M-Adoo** [comment]
@caizixian 我简单看了一下，举得如果官方有项目，我们做下游才有优势。不然看不出比现在这儿有什么优势的，流行度也是个硬伤。

**Comment by liigo** [comment]
Transifex连断句都做不好，我想不出要用它的理由。而且还有其他的问题。一个Transifex你连发了3个Issue，我都不知道要在哪里回复你好。参见别的Issue.
