### ISSUE TITLE
如何build翻译后的文档？

### ISSUE THREAD

**Issue by fasterpython** [rustcc/rust-zh#37]
以doc目录为例，看到很多 *.md文件，看文件的格式像是markdown语法。
如何简单高效的将这么多md文件生成一份更友好的文档呢?  

假定用户在这方面是个小白，或者不需要让每个人都折腾一遍。
希望答案能添加到readme.md中。

感谢你们的工作，非常感谢！

**Comment by liigo** [comment]
直接点击查看，GitHub自动以网页的形式展示出来
